Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.0.0.2/libexec/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 243, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
  File "/usr/local/Cellar/ansible/2.0.0.2/libexec/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 211, in _winrm_exec
    self.protocol.cleanup_command(self.shell_id, command_id)
  File "/usr/local/Cellar/ansible/2.0.0.2/libexec/vendor/lib/python2.7/site-packages/winrm/protocol.py", line 290, in cleanup_command
    rs = self.send_message(xmltodict.unparse(rq))
  File "/usr/local/Cellar/ansible/2.0.0.2/libexec/vendor/lib/python2.7/site-packages/winrm/protocol.py", line 193, in send_message
    return self.transport.send_message(message)
  File "/usr/local/Cellar/ansible/2.0.0.2/libexec/vendor/lib/python2.7/site-packages/winrm/transport.py", line 125, in send_message
    raise UnauthorizedError(transport='plaintext', message=ex.msg)
UnauthorizedError: 401 Unauthorized. 
fatal: [192.168.1.11]: FAILED! => {"failed": true, "msg": "ERROR! failed to exec cmd PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgBSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAiAEMAOgBcAFUAcwBlAHIAcwBcAHYAYQBnAHIAYQBuAHQAXABBAHAAcABEAGEAdABhAFwATABvAGMAYQBsAFwAVABlAG0AcABcAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA2ADQAMgA2ADkANAA2ADQALgAyADEALQAyADYAMAAyADYAMQA2ADEAMQAwADQAOQA1ADcAMgAiACAALQBGAG8AcgBjAGUAIAAtAFIAZQBjAHUAcgBzAGUAOwA="}
